[package]
name = "app"
version = "0.1.0"
description = "bs redis desktop client"
authors = ["fuyoo"]
license = "MIT"
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-rc.12", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-beta.8", features = ["api-all", "system-tray"] }
uuid = { version = "0.8.2", features = ['v4'] }
lazy_static = "1.4.0"
parking_lot = "0.11.2"
rusqlite = { version = "0.25.1", features = ["bundled"] }
log = "0.4.0"
env_logger = "0.8.4"
redis = "0.21.3"
anyhow = "1.0.44"
tokio = { version = "1", features = ["full"] }
libc = "0.2.106"

[target.'cfg(windows)'.dependencies]
windows = {version="^0.24", features= [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging"
] }
winreg = "0.10.1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]


