[package]
name = "rd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sciter-rs = "*"
tokio = { version = "1", features = ["full"] }
anyhow = "1"


[build-dependencies]
embed-resource="*"